apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    app: sai
  template:
    metadata:
      name: nginx
      labels:
        app: sai
    spec:
      containers:
      - name: nginx
        image: httpd:latest
        ports:
        - containerPort: 80
