apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: viewer-rolebinding
  namespace: demo
subjects:
- kind: ServiceAccount
  name: sa-viewer
  namespace: demo
roleRef:
apiGroup: rbac.authorization.k8s.io
 kind: Role
 name: role-viewer
