apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-pd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: test-container
        volumeMounts:
        - mountPath: /sai
          name: hp-volume
      volumes:
      - name: hp-volume
        hostPath:
          path: /data/sai
